// This table mirrors the allocation-relevant request schemas generated by
// opentelemetry-proto 0.31.0. Cargo.toml pins that version as an upgrade gate.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) enum Schema {
    TraceRequest,
    ResourceSpans,
    ScopeSpans,
    Span,
    SpanEvent,
    SpanLink,
    Status,
    LogsRequest,
    ResourceLogs,
    ScopeLogs,
    LogRecord,
    MetricsRequest,
    ResourceMetrics,
    ScopeMetrics,
    Metric,
    Gauge,
    Sum,
    Histogram,
    ExponentialHistogram,
    Summary,
    NumberPoint,
    HistogramPoint,
    ExponentialPoint,
    Buckets,
    SummaryPoint,
    Quantile,
    Exemplar,
    Resource,
    EntityRef,
    Scope,
    KeyValue,
    AnyValue,
    ArrayValue,
    KeyValueList,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) enum MessageCount {
    None,
    Structure,
    Primary,
    Attribute,
    AnyValue,
    ArrayItem,
    NestedAttribute,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) enum Field {
    Varint,
    Fixed32,
    Fixed64,
    String { structure: bool },
    Bytes,
    Message(Schema, MessageCount),
    RepeatedVarintStructure,
    RepeatedFixed64Structure,
}

impl Field {
    pub(super) fn duplicate_needs_structure(self) -> bool {
        matches!(
            self,
            Self::String { structure: false } | Self::Bytes | Self::Message(_, MessageCount::None)
        )
    }
}

use Field::{Bytes, Fixed32, Fixed64, Message, RepeatedFixed64Structure, RepeatedVarintStructure};
use MessageCount::{
    AnyValue as CountAnyValue, ArrayItem, Attribute, NestedAttribute, None as NoCount, Primary,
    Structure,
};
use Schema::*;

const STRING: Field = Field::String { structure: false };
const STRUCTURED_STRING: Field = Field::String { structure: true };

pub(super) fn field(schema: Schema, tag: u32) -> Option<Field> {
    match schema {
        TraceRequest => match tag {
            1 => Some(Message(ResourceSpans, Structure)),
            _ => None,
        },
        ResourceSpans => match tag {
            1 => Some(Message(Resource, Structure)),
            2 => Some(Message(ScopeSpans, Structure)),
            3 => Some(STRING),
            _ => None,
        },
        ScopeSpans => match tag {
            1 => Some(Message(Scope, Structure)),
            2 => Some(Message(Span, Primary)),
            3 => Some(STRING),
            _ => None,
        },
        Span => trace_span_field(tag),
        SpanEvent => match tag {
            1 => Some(Fixed64),
            2 => Some(STRING),
            3 => Some(Message(KeyValue, Attribute)),
            4 => Some(Field::Varint),
            _ => None,
        },
        SpanLink => match tag {
            1 | 2 => Some(Bytes),
            3 => Some(STRING),
            4 => Some(Message(KeyValue, Attribute)),
            5 => Some(Field::Varint),
            6 => Some(Fixed32),
            _ => None,
        },
        Status => match tag {
            2 => Some(STRING),
            3 => Some(Field::Varint),
            _ => None,
        },
        LogsRequest => match tag {
            1 => Some(Message(ResourceLogs, Structure)),
            _ => None,
        },
        ResourceLogs => match tag {
            1 => Some(Message(Resource, Structure)),
            2 => Some(Message(ScopeLogs, Structure)),
            3 => Some(STRING),
            _ => None,
        },
        ScopeLogs => match tag {
            1 => Some(Message(Scope, Structure)),
            2 => Some(Message(LogRecord, Primary)),
            3 => Some(STRING),
            _ => None,
        },
        LogRecord => log_record_field(tag),
        MetricsRequest => match tag {
            1 => Some(Message(ResourceMetrics, Structure)),
            _ => None,
        },
        ResourceMetrics => match tag {
            1 => Some(Message(Resource, Structure)),
            2 => Some(Message(ScopeMetrics, Structure)),
            3 => Some(STRING),
            _ => None,
        },
        ScopeMetrics => match tag {
            1 => Some(Message(Scope, Structure)),
            2 => Some(Message(Metric, Structure)),
            3 => Some(STRING),
            _ => None,
        },
        Metric => metric_field(tag),
        Gauge => match tag {
            1 => Some(Message(NumberPoint, Primary)),
            _ => None,
        },
        Sum => match tag {
            1 => Some(Message(NumberPoint, Primary)),
            2 | 3 => Some(Field::Varint),
            _ => None,
        },
        Histogram => match tag {
            1 => Some(Message(HistogramPoint, Primary)),
            2 => Some(Field::Varint),
            _ => None,
        },
        ExponentialHistogram => match tag {
            1 => Some(Message(ExponentialPoint, Primary)),
            2 => Some(Field::Varint),
            _ => None,
        },
        Summary => match tag {
            1 => Some(Message(SummaryPoint, Primary)),
            _ => None,
        },
        NumberPoint => number_point_field(tag),
        HistogramPoint => histogram_point_field(tag),
        ExponentialPoint => exponential_point_field(tag),
        Buckets => match tag {
            1 => Some(Field::Varint),
            2 => Some(RepeatedVarintStructure),
            _ => None,
        },
        SummaryPoint => match tag {
            2..=5 => Some(Fixed64),
            6 => Some(Message(Quantile, Structure)),
            7 => Some(Message(KeyValue, Attribute)),
            8 => Some(Field::Varint),
            _ => None,
        },
        Quantile => match tag {
            1 | 2 => Some(Fixed64),
            _ => None,
        },
        Exemplar => match tag {
            2 | 3 | 6 => Some(Fixed64),
            4 | 5 => Some(Bytes),
            7 => Some(Message(KeyValue, Attribute)),
            _ => None,
        },
        Resource => match tag {
            1 => Some(Message(KeyValue, Attribute)),
            2 => Some(Field::Varint),
            3 => Some(Message(EntityRef, Structure)),
            _ => None,
        },
        EntityRef => match tag {
            1 | 2 => Some(STRING),
            3 | 4 => Some(STRUCTURED_STRING),
            _ => None,
        },
        Scope => match tag {
            1 | 2 => Some(STRING),
            3 => Some(Message(KeyValue, Attribute)),
            4 => Some(Field::Varint),
            _ => None,
        },
        KeyValue => match tag {
            1 => Some(STRING),
            2 => Some(Message(AnyValue, CountAnyValue)),
            _ => None,
        },
        AnyValue => match tag {
            1 => Some(STRING),
            2 | 3 => Some(Field::Varint),
            4 => Some(Fixed64),
            5 => Some(Message(ArrayValue, NoCount)),
            6 => Some(Message(KeyValueList, NoCount)),
            7 => Some(Bytes),
            _ => None,
        },
        ArrayValue => match tag {
            1 => Some(Message(AnyValue, ArrayItem)),
            _ => None,
        },
        KeyValueList => match tag {
            1 => Some(Message(KeyValue, NestedAttribute)),
            _ => None,
        },
    }
}

fn trace_span_field(tag: u32) -> Option<Field> {
    match tag {
        1 | 2 | 4 => Some(Bytes),
        3 | 5 => Some(STRING),
        6 | 10 | 12 | 14 => Some(Field::Varint),
        7 | 8 => Some(Fixed64),
        9 => Some(Message(KeyValue, Attribute)),
        11 => Some(Message(SpanEvent, Structure)),
        13 => Some(Message(SpanLink, Structure)),
        15 => Some(Message(Status, Structure)),
        16 => Some(Fixed32),
        _ => None,
    }
}

fn log_record_field(tag: u32) -> Option<Field> {
    match tag {
        1 | 11 => Some(Fixed64),
        2 | 7 => Some(Field::Varint),
        3 | 12 => Some(STRING),
        5 => Some(Message(AnyValue, CountAnyValue)),
        6 => Some(Message(KeyValue, Attribute)),
        8 => Some(Fixed32),
        9 | 10 => Some(Bytes),
        _ => None,
    }
}

fn metric_field(tag: u32) -> Option<Field> {
    match tag {
        1..=3 => Some(STRING),
        5 => Some(Message(Gauge, Structure)),
        7 => Some(Message(Sum, Structure)),
        9 => Some(Message(Histogram, Structure)),
        10 => Some(Message(ExponentialHistogram, Structure)),
        11 => Some(Message(Summary, Structure)),
        12 => Some(Message(KeyValue, Attribute)),
        _ => None,
    }
}

fn number_point_field(tag: u32) -> Option<Field> {
    match tag {
        2 | 3 | 4 | 6 => Some(Fixed64),
        5 => Some(Message(Exemplar, Structure)),
        7 => Some(Message(KeyValue, Attribute)),
        8 => Some(Field::Varint),
        _ => None,
    }
}

fn histogram_point_field(tag: u32) -> Option<Field> {
    match tag {
        2 | 3 | 4 | 5 | 11 | 12 => Some(Fixed64),
        6 | 7 => Some(RepeatedFixed64Structure),
        8 => Some(Message(Exemplar, Structure)),
        9 => Some(Message(KeyValue, Attribute)),
        10 => Some(Field::Varint),
        _ => None,
    }
}

fn exponential_point_field(tag: u32) -> Option<Field> {
    match tag {
        1 => Some(Message(KeyValue, Attribute)),
        2 | 3 | 4 | 5 | 7 | 12 | 13 | 14 => Some(Fixed64),
        6 | 10 => Some(Field::Varint),
        8 | 9 => Some(Message(Buckets, Structure)),
        11 => Some(Message(Exemplar, Structure)),
        _ => None,
    }
}
